### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TimLeeCV** [Wu-ZJ/DSGNN#1]
Dear Author,

I am very interested in the network introduced in this paper. As a beginner in this field, may I ask in which file the code implementation for this paper is located?

Best regards.

**Comment by Wu-ZJ** [comment]
Sorry for my late reply. The model file is in DSGNN/mmdet/models/dense_heads/mask2former_sor_gnn_head.py

**Comment by TimLeeCV** [comment]
Thanks~！

> Sorry for my late reply. The model file is in DSGNN/mmdet/models/dense_heads/mask2former_sor_gnn_head.py
