### ISSUE TITLE
单gpu测试时，可视化报错

### ISSUE THREAD

**Issue by wulayu** [Wu-ZJ/DSGNN#3]
我在使用单gpu测试，想输出可视化结果时，似乎result[i]传入到show_result的格式有一点问题，np.full(bbox.shape[0], i, dtype=np.int32) AttributeError: 'str' object has no attribute 'shape'，请问是我哪里没设置对吗

**Comment by d-yjc** [comment]
Hello, is there a solution for this? I am facing the same issue.
